(setq calendar-week-start-day 1
      calendar-day-name-array ["niedziela" "poniedziałek" "wtorek" "środa" "czwartek" "piątek" "sobota"]
      calendar-month-name-array ["styczeń" "luty" "marzec" "kwiecięń" "maj" "czerwiec" "lipiec" "sierpień" "wrzesień" "październik" "listopad" "grudzień"])

(setq czas-letni
      `((holiday-float 3 0 -1 "Zmiana czasu na letni 1h do przodu")
	(holiday-float 10 0 -1 "Zmiana czasu na zimowy 1h do tyłu")))

(setq swieta-panstwowe-pozostałe-święta
      `((holiday-fixed 2 8 "Święto Służby Więziennej")
	(holiday-fixed 5 2 "Dzień Flagi Rzeczypospolitej Polskiej; Dzień Polonii i Polaków za Granicą")
	(holiday-fixed 5 9 "Narodowe Święto Zwycięstwa i Wolności")
	(holiday-fixed 5 16 "Święto Straży Granicznej")
	(holiday-fixed 6 12 "Święto BOR")
	(holiday-fixed 7 24 "Święto Policji")
	(holiday-fixed 7 31 "Dzień Skarbowości")
	(holiday-fixed 8 1 "Narodowy Dzień Pamięci Powstania Warszawskiego")
	(holiday-fixed 8 15 "Święto Wojska Polskiego")
	(holiday-fixed 8 29 "Dzień Straży Gminnej")
	(holiday-fixed 8 31 "Dzień Solidarności i Wolności")
	(holiday-fixed 9 1 "Dzień Weterana")
	(holiday-fixed 9 21 "Dzień Służby Celnej")
	(holiday-fixed 10 14 "Dzień Edukacji Narodowej")
	(holiday-fixed 10 16 "Dzień Papieża Jana Pawła II")
	(holiday-fixed 11 21 "Dzień Pracownika Socjalnego")))

(setq ustawowo-wolne-od-pracy
      `((holiday-fixed 1 1 "Nowy Rok")
	(holiday-easter-etc 0 "Pierwszy dzień Wielkanocy")
	(holiday-easter-etc 1 "Drugi dzień Wielkanocy")
	(holiday-fixed 5 1 "Święto Państwowe")
	(holiday-fixed 5 3 "Święto Narodowe Trzeciego Maja")
	(holiday-easter-etc 50 "Zielone świątki")
	(holiday-easter-etc 60 "Boże Ciało")
	(holiday-fixed 8 15 "Wniebowzięcie Najświętrzej Maryi Panny")
	(holiday-fixed 11 1 "Wszystkich Świętych")
	(holiday-fixed 11 11 "Narodowe Święto Niepodległości")
	(holiday-fixed 12 25 "pierwszy dzień Bożego Narodzenia")
	(holiday-fixed 12 26 "drugi dzień Bożego Narodzenia")))

(setq swieta-katolickie
      `((holiday-fixed 1 1 "Światowy Dzień Pokoju (od 1967); Bożej Rodzicielki Maryi")
	(holiday-fixed 1 6 "Trzech Króli, Objawienie Pańskie (do 1960 dzień wolny od pracy)")
	(holiday-fixed 1 17 "Dzień Judaizmu")
	(holiday-fixed 1 18 "rozpoczyna się Tydzień Modlitw o Jedność Chrześcijan (do 25 stycznia)")
	(holiday-fixed 1 24 "Światowy Dzień Środków Społecznego Przekazu")
	(holiday-fixed 1 25 "Nawrócenie św. Pawła, Apostoła (ostatni dzień Modlitw o Jedność Chrześcijan)")
	(holiday-fixed 1 26 "Dzień Islamu")
	(holiday-easter-etc -52 "Tłusty Czwartek")
	(holiday-easter-etc -46 "Popielec, Środa Popielcowa")
	(holiday-fixed 2 2 "Światowy Dzień Życia Konsekrowanego (od 1997); Ofiarowanie Pańskie, Matki Boskiej Gromnicznej")
	(holiday-fixed 2 11 "Światowy Dzień Chorego")
	(holiday-fixed 2 14 "Dzień św. Cyryla i św. Metodego (święto patronów Europy)")
	(holiday-fixed 2 22 "Katedry św. Piotra, Apostoła")
	(holiday-easter-etc -7 "Światowy Dzień Młodzieży, Niedziela Palmowa")
	(holiday-easter-etc -6 "Dzień Trzeźwości, Ogólnopolski Dzień Trzeźwości")
	(holiday-easter-etc 0 "Wielkanoc, Zmartwychwstanie Pańskie - Niedziela Wielkanocna")
	(holiday-easter-etc 1 "Poniedziałek Wielkanocny")
	(holiday-fixed 3 4 "Dzień św. Kazimierza Królewicza (święto patrona Polski)")
	(holiday-fixed 3 19 "Dzień Świętego Józefa")
	(holiday-fixed 3 25 "Dzień Świętości Życia; Zwiastowanie Pańskie")
	(holiday-fixed 3 26 "Dzień Modlitw za Więźniów w dniu wspomnienia Dobrego Łotra patrona więźniów")
	(holiday-easter-etc 7 "Niedziela Miłosierdzia Bożego")
	(holiday-easter-etc 14 "Dzień Modlitw za Kierowców, Niedziela Modlitw za Kierowców")
	(holiday-easter-etc 21 "Światowy Dzień Modlitw o Powołania")
	(holiday-fixed 4 23 "Dzień św. Wojciecha (święto głównego patrona Polski)")
	(holiday-fixed 4 25 "Dzień św. Marka Ewangelisty")
	(holiday-fixed 4 29 "Dzień św. Katarzyny ze Sieny (święto patronki Europy)")
	(holiday-easter-etc 40 "Wniebowstąpienie Pańskie")
	(holiday-easter-etc 50 "Zesłanie Ducha Świętego - potocznie Zielone Świątki")
	(holiday-easter-etc 51 "Najświętszej Maryi Panny, Matki Kościoła")
	(holiday-easter-etc 57 "Najświętszej Trójcy")
	(holiday-easter-etc 61 "Boże Ciało, Najświętszego Ciała i Krwi Pańskiej")
	(holiday-fixed 5 3 "Najświętszej Marii Panny Królowej Polski (święto głównej patronki Polski)")
	(holiday-fixed 5 6 "Święto Apostołów: Filipa i Jakuba Młodszego")
	(holiday-fixed 5 8 "Dzień św. Stanisława ze Szczepanowa (święto głównego patrona Polski)")
	(holiday-fixed 5 14 "Dzień św. Macieja, Apostoła")
	(holiday-fixed 5 16 "Dzień św. Andrzeja Boboli (święto patrona Polski; uroczystość w metropolii warszawskiej)")
	(holiday-fixed 5 31 "Nawiedzenie Najświętszej Maryi Panny")
	(holiday-fixed 6 23 "Wigilia św. Jana, Noc Świętojańska (noc z 23 na 24 czerwca, obchodzona w wigilię św. Jana Chrzciciela)")
	(holiday-fixed 6 24 "Narodzenie św. Jana Chrzciciela")
	(holiday-fixed 6 29 "Dzień świętych Apostołów: Piotra i Pawła")
	(holiday-fixed 7 3 "Dzień św. Tomasza Apostoła")
	(holiday-fixed 7 11 "Dzień św. Benedykta z Nursji (święto patrona Europy)")
	(holiday-fixed 7 23 "Dzień św. Brygidy (święto patronki Europy)")
	(holiday-fixed 7 25 "Dzień św. Jakuba Starszego, Apostoła; Dzień Bezpiecznego Kierowcy w dniu wspomnienia patrona św. Krzysztofa")
	(holiday-fixed 8 6 "Przemienienie Pańskie")
	(holiday-fixed 8 9 "Dzień św. Teresy Benedykty od Krzyża (święto patronki Europy)")
	(holiday-fixed 8 10 "Dzień św. Wawrzyńca (również święto diakonatu; uroczystość w diecezji pelplińskiej)")
	(holiday-fixed 8 15 "Wniebowzięcie Najświętszej Maryi Panny (dzień wolny od pracy)")
	(holiday-fixed 8 24 "Dzień św. Bartłomieja, Apostoła")
	(holiday-fixed 8 26 "Najświętszej Maryi Panny Częstochowskiej, Matki Boskiej Częstochowskiej")
	(holiday-fixed 9 8 "Narodzenie Najświętszej Maryi Panny")
	(holiday-fixed 9 14 "Podwyższenie Krzyża Świętego")
	(holiday-fixed 9 18 "Dzień św. Stanisława Kostki (święto patrona Polski; na świecie 13 listopada)")
	(holiday-fixed 9 21 "Dzień św. Mateusza, Apostoła i Ewangelisty")
	(holiday-fixed 9 29 "Dzień św. Archaniołów: Michała, Rafała i Gabriela")
	(holiday-fixed 10 16 "Rocznica pontyfikatu Jana Pawła II")
	(holiday-fixed 10 18 "Dzień św. Łukasza, Ewangelisty")
	(holiday-fixed 10 28 "Dzień świętych Apostołów: Szymona i Judy Tadeusza")
	(holiday-fixed 11 1 "Wszystkich Świętych (dzień wolny od pracy)")
	(holiday-fixed 11 2 "Dzień Zaduszny, Wspomnienie wszystkich wiernych zmarłych (uznawany przez chrześcijan za święto)")
	(holiday-fixed 11 9 "Rocznica poświęcenia bazyliki laterańskiej")
	(holiday-fixed 11 30 "Dzień św. Andrzeja Apostoła (uroczystość w archidiecezji warmińskiej)")
	(holiday-fixed 12 8 "Niepokalane Poczęcie Najświętszej Maryi Panny")
	(holiday-fixed 12 25 "Boże Narodzenie, Narodzenie Pańskie")
	(holiday-fixed 12 26 "Dzień św. Szczepana, Pierwszego Męczennika")
	(holiday-fixed 12 27 "Dzień św. Jana Apostoła i Ewangelisty")
	(holiday-fixed 12 28 "Dzień Świętych Młodzianków, Dzień Niewinnych Dzieci Betlejemskich")))
